general structure of Admin dahsboard is ready.Also FootballCourtDetai…
FiliciogluFurkan/falcons-ui pull request #22
Opened 2024-11-26 18:20 UTC by FiliciogluFurkan

…ls page implemented

2024-11-26 20:43 UTC, mehmethayrullahozkul requested changes
Üstünden geçilmeli.

2024-11-26 20:43 UTC, mehmethayrullahozkul commented on index.html
>    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
yani kodda iyileştirme yapılır burada kötüleştirme yapılmış herhalde?

2024-11-26 20:43 UTC, mehmethayrullahozkul commented on src/components/CommentOfCourts.tsx
> +
Ayrı bir interfaces gibi bir klasörün altına taşınmalı, review birden fazla yerde kullanılacak bir interface.

2024-11-26 20:43 UTC, mehmethayrullahozkul commented on src/components/ReservationSystem.tsx
> +  return (
Date operasyonları kendi DateUtils.tsx gibi bir dosyadan kullanılabilir, birden fazla yerde kullanılacak.

2024-11-26 20:43 UTC, mehmethayrullahozkul commented on src/components/admindashboardcomponents/AdminAccount.tsx
> +
Bunun işlevi nedir? İstenen bir durum mu?

2024-11-26 20:43 UTC, mehmethayrullahozkul commented on src/components/admindashboardcomponents/AdminAccount.tsx
> +
Tamam boş olduğu için herhalde geri alıyorum sorun yok.

2024-11-26 20:43 UTC, mehmethayrullahozkul commented on src/components/admindashboardcomponents/FootballCourtDetails.tsx
> +    </Box>
Kullanılmayan kodu silelim boş yer kaplamasın.

2024-11-26 20:43 UTC, mehmethayrullahozkul commented on src/components/admindashboardcomponents/FootballCourtDetails.tsx
> +                    <Box>
Kodda Türkçe, İngilizce labeller karışık girilmiş, İngilizce yapalım.

2024-11-26 20:43 UTC, mehmethayrullahozkul commented on src/components/admindashboardcomponents/FootballCourtDetails.tsx
> +export default TesisYonetim;
İngilizce pls.

2024-11-26 20:43 UTC, mehmethayrullahozkul commented on src/components/admindashboardcomponents/FootballCourtsCommentsCards.tsx
> +}
Mesela yukarıda review olarak tanımlanmıştı burada tekrar bir comment geliyor, isimlendirmede istikrar, ayrı bir sayfada olsa bunlar olmaz sanki

2024-11-26 20:43 UTC, mehmethayrullahozkul commented on src/pages/About.tsx
Sanki bunu her yerde kullansak düz fonksiyon yerine?

2024-11-27 14:22 UTC, omerfarukorc approved these changes

2024-11-27 15:40 UTC, mehmethayrullahozkul approved these changes

2024-11-27 15:41 UTC, merged