UI improvements for dashboard
FiliciogluFurkan/falcons-ui pull request #36
Opened 2024-12-05 23:36 UTC by omerfarukorc

# Dashboard UI İyileştirmeleri

## Yapılan Değişiklikler
- Admin Dashboard için Header gizlendi
- Çıkış Yap butonu sidebara eklenerek Adminin çıkış yapması sağlandı
- Dashboard kartlarının düzeni ve hizalaması iyileştirildi
- Yorum kartlarının responsive tasarımı düzeltildi
- Kartlardaki hizalama ve okunma sorunu çözüldü.
- Puanlamalar için sabit ondalık format eklendi
- Yorum kartlarındaki boşluklar ve hizalamalar düzenlendi
- Uzun isimler için alt satıra geçme önlendi

## Test Edildi
- Farklı ekran boyutlarında responsive tasarım kontrol edildi
- Yorum kartlarındaki puanlamaların doğru görüntülendiği kontrol edildi

2024-12-05 23:54 UTC, mehmethayrullahozkul requested changes

2024-12-05 23:54 UTC, mehmethayrullahozkul commented on src/admin/components/dashboard/Dashboard.tsx
>        </Box>
Bu comment yapısı birden fazla yerde kullanılacak, böyle her seferinde yapmak yerine CourtsCommentsCarts componenti üzerinde geliştirme yapıp oradan kullanılabilir mi?

2024-12-05 23:54 UTC, mehmethayrullahozkul commented on src/admin/pages/DashboardTemplate.tsx
> +                fontWeight: 700,
Böyle bi family yok sanki, sadece 'Barlow'u kabul etmiyor mu?

2024-12-05 23:55 UTC, omerfarukorc commented on src/admin/components/dashboard/Dashboard.tsx
>        </Box>
evet kullanılabilir.

2024-12-05 23:56 UTC, mehmethayrullahozkul commented on src/admin/components/dashboard/Dashboard.tsx
>        </Box>
https://www.youtube.com/watch?v=F9uz2y3pVgg

2024-12-06 00:00 UTC, mehmethayrullahozkul approved these changes

2024-12-06 00:01 UTC, merged