refactor ve court fetch baglantisi yapildi.
FiliciogluFurkan/falcons-ui pull request #38
Opened 2024-12-07 12:50 UTC by FiliciogluFurkan

2024-12-07 13:10 UTC, mehmethayrullahozkul requested changes
eline sağlık ama değiştirilmesi gereken yerler var

2024-12-07 13:10 UTC, mehmethayrullahozkul commented on src/admin/components/comments/Comments.tsx
> +};
`renderStars` fonksiyonu `src/services/CommentService.tsx` altına koyulmuştu, tekrar tekrar deklare edilmemeli o dosyadan import edilmeli.

2024-12-07 13:10 UTC, mehmethayrullahozkul commented on src/admin/components/comments/Comments.tsx
>      {
`const Comments = (): JSX.Element => { ` elementine çevirmel, projenin kalanına uyumlu olmalı.

2024-12-07 13:10 UTC, mehmethayrullahozkul commented on src/admin/components/comments/Comments.tsx
>                  </Box>
Artık comment ile review ayrımı olmalı, yani ya hepsi comment olarak ya da review olarak değiştirilmeli bir yerde comment bir yerde review olmamalı.

2024-12-07 13:10 UTC, mehmethayrullahozkul commented on src/admin/components/my-courts/MyCourts.tsx
> +
Zaten bizde bir tema varken burada ayrı bir tema oluşturmak neden?

2024-12-07 13:10 UTC, mehmethayrullahozkul commented on src/admin/components/my-courts/MyCourts.tsx
> +const ReservationSystem = () => {
JSX.Element olarak değiştirilmeli.

2024-12-07 13:10 UTC, mehmethayrullahozkul commented on src/admin/components/my-courts/MyCourts.tsx
> +  };
src/services/TimeServices.tsx dosyası oluşturulup, altına taşınmalı, birden çok yerde kullanılacak fonksiyonları tekrar tekrar her dosyaya yazıyoruz

2024-12-07 13:10 UTC, mehmethayrullahozkul commented on src/admin/components/my-courts/MyCourts.tsx
> +      <Box sx={{ margin: 2, padding: 2, border: '1px solid #ccc', borderRadius: 2, backgroundColor: '#424242' }}>
Kendi başına bir Theme'e sarılmamalı, applikasyon zaten bir ThemeProvider'ın içinde nested theme'ler oluşturulmamalı.

2024-12-07 13:10 UTC, mehmethayrullahozkul commented on src/admin/components/my-courts/MyCourts.tsx
> +
Eğer bu interface'ler birden fazla rezervasyon alanında kullanılacaksa ki bende time slot öyle, `src/interfaces/` altına konulmalı, user belki konulmayabilir.

2024-12-07 13:10 UTC, mehmethayrullahozkul commented on src/admin/components/reservations/Reservations.tsx
> +}
Randevu `src/interfaces/ `altına konulmalı.

2024-12-07 13:10 UTC, mehmethayrullahozkul commented on src/admin/pages/DashboardTemplate.tsx
> +import ManageFacility from "../components/manage-facility/ManageFacility";
Relative path vermekten mümkün olduğunda çekinilmeli `@/admin/components/manage-facility/ManageFacility` ya da `src/admin/components/manage-facility/ManageFacility` olarak verilmeli, sayfanın hangi paket altında olduğu daha anlaşılır oluyor.

2024-12-07 14:24 UTC, FiliciogluFurkan commented on src/admin/components/my-courts/MyCourts.tsx
> +  };
bu zaten db bağlandığı zaman silinecektir.

2024-12-08 10:19 UTC, mehmethayrullahozkul approved these changes

2024-12-08 10:19 UTC, mehmethayrullahozkul commented on src/interfaces/Randevu.tsx
> +export interface Randevu {
Neden İngilizce değil de randevu? Reservation?

2024-12-08 10:34 UTC, merged